version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset_2019:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_2019.py
        --output output/dataset_2019.arrow
    outputs:
      highly_sensitive:
        cohort: output/dataset_2019.arrow

  generate_dataset_2020:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_2020.py
        --output output/dataset_2020.arrow
    outputs:
      highly_sensitive:
        cohort: output/dataset_2020.arrow

  generate_dataset_2021:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_2021.py
        --output output/dataset_2021.arrow
    outputs:
      highly_sensitive:
        cohort: output/dataset_2021.arrow

  generate_dataset_2022:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_2022.py
        --output output/dataset_2022.arrow
    outputs:
      highly_sensitive:
        cohort: output/dataset_2022.arrow

  generate_dataset_2023:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_2023.py
        --output output/dataset_2023.arrow
    outputs:
      highly_sensitive:
        cohort: output/dataset_2023.arrow

  generate_report_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/notebooks/summarise_dataset.ipynb --execute --to html --output-dir=/workspace/output --no-input --ExecutePreprocessor.timeout=86400
    needs: [generate_dataset_2019, generate_dataset_2020, generate_dataset_2021, generate_dataset_2022, generate_dataset_2023]
    outputs:
      moderately_sensitive:
        notebook: output/summarise_dataset.html
        prescribing_tables: output/prescribing*.csv
        totals_tables: output/totals*.csv